project:
  type: book
book:
  title: Mechanical Engineering Metrology and Measurements (MEMM)
  author: Alex Liberzon
  chapters:
  - index.qmd
  - part: "Theory of metrology"
    chapters: 
      - theory/index.qmd
      - calibration/index.qmd
  - part: "Statistics"
    chapters:
      - statistics/index.qmd
  - part: "Signal Processing"
    chapters:
      - signal_processing/index.qmd
      - a2d/index.qmd
  - part: "Dynamic Signals"
    chapters:
      - dynamic_signals/index.qmd
  
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: img/logo.png

bibliography: references.bib
