project:
  type: book

book:
  title: Mechanical Engineering Metrology and Measurements (MEMM)
  author: Alex Liberzon
  page-footer: CC-BY-SA-4.0 (2025) Alex Liberzon
  repo-url: https://github.com/alexlib/mechanical-engineering-metrology-and-measurements
  page-navigation: true
  chapters:
  - index.qmd
  - part: "Theory of metrology"
    chapters: 
      - theory/index.qmd
      - calibration/index.qmd
  - part: "Statistics"
    chapters:
      - statistics/index.qmd
  - part: "Signal Processing"
    chapters:
      - signal_processing/index.qmd
      - a2d/index.qmd
  - part: "Dynamic Signals"
    chapters:
      - dynamic_signals/index.qmd
  - references.qmd
  
format:
  html:
    theme: cosmo
    number-sections: true
    number-depth: 4
    toc-depth: 4

  # pdf:
  #   documentclass: report
  # epub:
  #   cover-image: img/logo.png



bibliography: references.bib
